### ISSUE TITLE
do not parse unassigned bugs

### ISSUE THREAD

**Issue by asarubbo** [kensington/bugbot#12]
While bugs are assigned to wranglers, we should not add the sanity flag+ because we don't know what happened and/or if the maintainer agrees.

example: https://bugs.gentoo.org/show_bug.cgi?id=607508

**Comment by asarubbo** [comment]
Also, an hint that comes from this bug:

Before getatoms the stablereq were processed more slowly, so if someone opened a stablereq and CC'ed arches, maybe the maintainer had the time to un'CC if he didn't agree.
Right now, the bot applies the flag after few minutes and the requests are processed fastly.

How to do not lose the control on who adds arches?

**Comment by kensington** [comment]
I updated the bot to ignore any bugs assigned to bug-wranglers.
