### ISSUE TITLE
A corner case failure

### ISSUE THREAD

**Issue by asarubbo** [kensington/bugbot#2]
Getatoms for ppc fetches the following:
```
# bug #584650
=app-admin/cgmanager-0.41
```

But repoman fails in the following way:

```
  dependency.bad [fatal]        28
   app-admin/cgmanager/cgmanager-0.41.ebuild: DEPEND: ppc(default/linux/powerpc/ppc32/13.0)
['sys-libs/libnih[dbus]']
```

The question is: has something been changed after the sanity check was passed or there is a failure somewhere?

**Comment by kensington** [comment]
Unfortunately while fixing an issue with handling strange formats in the atom field, I introduced a regression that caused repoman to be run with ``--include-arches=""``. I've fixed the bug now, and have rerun the bot on some requests incorrectly marked as valid I found.

**Comment by kensington** [comment]
The fix seems to have held.
