### ISSUE TITLE
Please consider to make the script able to work with the TESTFILE global variable

### ISSUE THREAD

**Issue by asarubbo** [kensington/bugbot#4]
Actually, getatoms prints to stdout and it is fine add > $FILE to redirect the output.

If we have a situation where getatoms writes into a file defined as TESTFILE, the main goal is that the future batch_stabilize will look at $TESTFILE too instead of manually specifying the file to both script.

Note: the TESTFILE variable can have a better name like STABLELIST or whatever.

**Comment by kensington** [comment]
Thanks, added in 1125602c68e6f6ca65fca7a886d2c9af97d90c1d.
