### ISSUE TITLE
another corner case failure

### ISSUE THREAD

**Issue by asarubbo** [kensington/bugbot#5]
```
(chroot) vh ~ # python getatoms.py --stablereq -a sparc -b 574134
# bug #574134

(chroot) vh ~ # 
```

It printed an empty "atom" because in the bug we have spark instead of sparc

```
=dev-lisp/sbcl-1.3.11 amd64 ppc spark x86
=dev-lisp/uiop-3.1.5 spark
=dev-lisp/sbcl-1.3.11 spark
```

Probably the bug is not in the getatoms but in the bot which should not apply the sanity flags when there are unknown arches.

**Comment by asarubbo** [comment]
For now I'm leaving bug 574134 as-is to permit you do make the adequate tests on a real case.

**Comment by kensington** [comment]
Thanks, the bot should now be validating the arch list from now on.
