### ISSUE TITLE
--keywordreq and --stablereq should be required only if --all-bugs was specified

### ISSUE THREAD

**Issue by asarubbo** [kensington/bugbot#6]
I discovered this minor bug while testing for bug #5 

```
(chroot) vh ~ # python getatoms.py -a sparc -b 574134
usage: getatoms.py [-h] (--all-bugs | -b BUG) (--keywordreq | --stablereq)
                   [-a ARCH] [-n] [--no-sanity-check] [-s]
getatoms.py: error: one of the arguments --keywordreq --stablereq is required
```

I guess that --keywordreq --stablereq should be specified when --all-bugs is used, so to tell to the script if it needs to parse all stablereq or all keywordreq.
While specifying a single bug it should know the type of the request based on the Coponent.

Does it make sense?

Thx

**Comment by kensington** [comment]
Thanks, fixed in 6b5c40b4ae7667fafa5d53cf46b9ac1cafcd830d.
