### ISSUE TITLE
issue related to --no-depends

### ISSUE THREAD

**Issue by asarubbo** [kensington/bugbot#7]
This is a bit complicated, I don't know if we can implement what I will describe.

I'm trying to get all bugs from amd64 which includes bug 603574.

Unforunately bug 603574 has a depends on, so I will not obtain it using --no-depends.

The fact is:
this bug is not really blocked for amd64 which has libidn2 keyworded and it is not in CC.

How it should work if possible:
If there is depends on bug -> check if it is a stabilization or keywording -> if is one of those and the requested arch is not in CC, then the arch is not affected from this bug ( e.g. the arch has already stabilized/keyworded there).

We need to pay attention at the following scenario:
if someone will add a depends on and will not cc the arches in the bug, waiting for the maintainer, like to say: hey, this is a blocker, you need to know it but I don't want to CC arches by myself, so the first thing to avoid this failure is check if in the depends on bug, the field sanity-check is passed.

In any case, if something goes bad because of people that does not handle the bug correctly, repoman will catch the issue, or we will be notified by the maintainer.

What do you think?

**Comment by kensington** [comment]
This should be part of ba4d23197026b4c195d0ef3b88514af355e51aad. Let me know if there's any issues.

**Comment by asarubbo** [comment]
I created a real testcase.

I opened bug 606378 which has for example =net-analyzer/ettercap-0.8.2 as package list.
I opened bug 606380 which block 606378

While amd64 is CC'ed on 606380 I get as expected:
```
# bug #606378 depends on other unresolved bugs, skipping...
```

But while I remove from CC amd64 on 606380, I'm able to fetch the bug.


NOTE:
- in 606380 there is no package list filled
- in 606380 there is no sanity check+

So how to bu sure that amd64 does not need to do anything in 606380 ?

**Comment by leio** [comment]
One very bad case of this was still there when the dependent bug was a security bug, leading to higher level library security bug not being handled until lower level is done by ALL arches. But looks like your test didn't involve the security component. So I guess this is a note to update getatoms after kensington accepts my PR 14, if he does :D
